version: '3'

services:
  offensive-rezzer:
    image: bungdanar/offensive-rezzer
    restart: 'no'
    build: .
    volumes:
      - './api-spec:/usr/src/app/api-spec'
      - './output:/usr/src/app/output'
    env_file:
      - .env
